port = 8080

[vereinsflieger]
user = "user"
password = "password"

[recaptcha]
require = false
secret = "secret"

[mail]
user = "mail_user"
password = "mail_password"
host = "mail_host"
port = 25
sender = "mail_sender"
voucher_subject = "Gutschein angelegt"
voucher_template = """
{{.Salutation}}

Gutschein über Betrag {{.Value}}: angelegt: {{.Number}} {{.Owner}} angelegt.

Bitte Zahlen!
"""